### ISSUE TITLE
cannot find module ionic/storage

### ISSUE THREAD

**Issue by amnnzri** [jimmygzzmtz/Calories-Tracker#2]
when i run using ionic serve it show errorl in my cmd saying 'cannot find module ionic/storage'

im newbie here

**Comment by jimmygzzmtz** [comment]
If this is your first time using Ionic, you should know that you need to install all necessary modules (that are not included by default) in a project for it to compile. Please have a look at https://ionicframework.com/docs/building/storage/, specifically the "npm install --save @ionic/storage" part.

I also recommend reading Ionic Docs (https://ionicframework.com/docs), since it is a very good resource to see what components you can use, see code samples, list of modules, etc. Perhaps you should try the "Getting Started" with a blank app before you try to see how this sample app works?

Don't worry about being a "newbie", *everybody* starts somewhere.
